import maplibregl from 'https://esm.sh/maplibre-gl@6.0.0';
import { gpx } from 'https://esm.sh/@tmcw/togeojson@7.1.2';
import nearestPointOnLine from 'https://esm.sh/@turf/nearest-point-on-line@7.2.0';
import length from 'https://esm.sh/@turf/length@7.2.0';
import along from 'https://esm.sh/@turf/along@7.2.0';
import distance from 'https://esm.sh/@turf/distance@7.2.0';
import { lineString, point } from 'https://esm.sh/@turf/helpers@7.2.0';

const $=id=>document.getElementById(id);
const state={apiKey:localStorage.getItem('graphhopper-key')||'',route:null,original:[],mode:'idle',current:null,progressKm:0,offCount:0,lastReroute:0,watch:null,marker:null};
$('apiKey').value=state.apiKey;
const style={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap-bijdragers'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
const map=new maplibregl.Map({container:'map',style,center:[5.3,52.1],zoom:7});
map.addControl(new maplibregl.NavigationControl({showCompass:true}),'top-right');
map.on('load',()=>{for(const id of ['main-route','rejoin-route']){map.addSource(id,{type:'geojson',data:lineString([])});map.addLayer({id,type:'line',source:id,paint:{'line-color':id==='main-route'?'#2563eb':'#f97316','line-width':id==='main-route'?7:6,'line-opacity':.9}});}});
const status=t=>$('status').textContent=t;
const fmt=m=>m>=1000?`${(m/1000).toFixed(m>=10000?0:1)} km`:`${Math.max(10,Math.round(m/10)*10)} m`;
function ensureKey(){if(!state.apiKey.trim())throw Error('Vul eerst je GraphHopper API-key in bij Instellingen.');}
async function geocode(q){ensureKey();const u=new URL('https://graphhopper.com/api/1/geocode');u.searchParams.set('q',q);u.searchParams.set('locale','nl');u.searchParams.set('limit','5');u.searchParams.set('key',state.apiKey);const r=await fetch(u);if(!r.ok)throw Error(`Adres zoeken mislukt (${r.status}).`);const d=await r.json();return(d.hits||[]).map(h=>({label:[h.name,h.street,h.housenumber,h.city,h.country].filter(Boolean).join(', '),point:[h.point.lng,h.point.lat]}));}
async function route(points){ensureKey();const u=new URL('https://graphhopper.com/api/1/route');points.forEach(([lng,lat])=>u.searchParams.append('point',`${lat},${lng}`));for(const[k,v]of Object.entries({profile:'car',locale:'nl',instructions:'true',points_encoded:'false',calc_points:'true',key:state.apiKey}))u.searchParams.set(k,v);const r=await fetch(u);if(!r.ok)throw Error(`Routeberekening mislukt (${r.status}).`);const d=await r.json(),p=d.paths?.[0];if(!p)throw Error('Geen route gevonden.');return{coordinates:p.points.coordinates,distance:p.distance,time:p.time,instructions:p.instructions||[]};}
function draw(data,mode){state.route=data;state.mode=mode;const id=mode==='rejoin'?'rejoin-route':'main-route';map.getSource(id)?.setData(lineString(data.coordinates));if(data.coordinates.length){const b=data.coordinates.reduce((x,c)=>x.extend(c),new maplibregl.LngLatBounds(data.coordinates[0],data.coordinates[0]));map.fitBounds(b,{padding:70,duration:700});}$('mode').textContent=mode==='rejoin'?'Tijdelijke aansluitroute':mode==='gpx'?'GPX-navigatie':'Adresnavigatie';$('instruction').textContent=data.instructions?.[0]?.text||(mode==='gpx'?'Volg de blauwe GPX-route':'Volg de route');}
$('search').onclick=async()=>{try{status('Adres zoeken…');const hits=await geocode($('query').value.trim());$('results').innerHTML='';for(const h of hits){const b=document.createElement('button');b.className='result';b.textContent=h.label;b.onclick=async()=>{try{$('results').hidden=true;$('query').value=h.label;if(!state.current)throw Error('Start eerst GPS.');status('Route berekenen…');const d=await route([state.current,h.point]);state.original=d.coordinates;state.progressKm=0;draw(d,'address');status(`Route: ${fmt(d.distance)}`);}catch(e){status(e.message);}};$('results').appendChild(b);}$('results').hidden=false;status('Kies een bestemming');}catch(e){status(e.message);}};
$('query').addEventListener('keydown',e=>{if(e.key==='Enter')$('search').click();});
$('settings').onclick=()=>{$('sheet').hidden=false;$('backdrop').hidden=false;};$('backdrop').onclick=()=>{$('sheet').hidden=true;$('backdrop').hidden=true;};
$('saveSettings').onclick=()=>{state.apiKey=$('apiKey').value.trim();localStorage.setItem('graphhopper-key',state.apiKey);$('sheet').hidden=true;$('backdrop').hidden=true;status('Instellingen opgeslagen');};
$('gpx').onclick=()=>$('file').click();
$('file').onchange=async e=>{try{const f=e.target.files?.[0];if(!f)return;status('GPX laden…');const xml=new DOMParser().parseFromString(await f.text(),'application/xml');if(xml.querySelector('parsererror'))throw Error('Dit GPX-bestand kan niet worden gelezen.');const gj=gpx(xml),coords=[];for(const ft of gj.features){const g=ft.geometry;if(g?.type==='LineString')coords.push(...g.coordinates.map(c=>[c[0],c[1]]));if(g?.type==='MultiLineString')g.coordinates.forEach(l=>coords.push(...l.map(c=>[c[0],c[1]])));}if(coords.length<2)throw Error('Geen bruikbare track gevonden.');state.original=coords;state.progressKm=0;const d={coordinates:coords,distance:length(lineString(coords),{units:'kilometers'})*1000,time:0,instructions:[]};draw(d,'gpx');status(`GPX geladen: ${fmt(d.distance)}`);}catch(e){status(e.message);}};
$('clear').onclick=()=>{state.original=[];state.route=null;state.mode='idle';for(const id of['main-route','rejoin-route'])map.getSource(id)?.setData(lineString([]));$('instruction').textContent='Geen actieve route';$('mode').textContent='RouteRijder';status('Route gewist');};
function updateInstruction(pos){if(!state.route?.coordinates?.length||!state.route.instructions?.length)return;const snap=nearestPointOnLine(lineString(state.route.coordinates),point(pos),{units:'kilometers'}),idx=Number(snap.properties.index||0);const ins=state.route.instructions.find(i=>idx>=i.interval[0]&&idx<=i.interval[1])||state.route.instructions.find(i=>i.interval[0]>=idx);if(ins)$('instruction').textContent=`${fmt(ins.distance)} · ${ins.text}`;}
async function smartRejoin(pos){if(state.original.length<2||!state.apiKey||Date.now()-state.lastReroute<25000)return;state.lastReroute=Date.now();status('Slim aansluitpunt zoeken…');const l=lineString(state.original),total=length(l,{units:'kilometers'}),kms=[.5,1,2,4].map(v=>Math.min(total,state.progressKm+v)).filter((v,i,a)=>v>state.progressKm+.1&&a.indexOf(v)===i),scored=[];for(const km of kms){try{const p=along(l,km,{units:'kilometers'}).geometry.coordinates,d=await route([pos,p]);scored.push({score:d.distance+km*35,data:d,km});}catch{}}scored.sort((a,b)=>a.score-b.score);if(!scored[0])return status('Geen geschikte aansluiting gevonden');state.progressKm=scored[0].km;draw(scored[0].data,'rejoin');status(`Nieuwe aansluiting over ${fmt(scored[0].data.distance)}`);}
function onPosition(p){const pos=[p.coords.longitude,p.coords.latitude];state.current=pos;if(!state.marker)state.marker=new maplibregl.Marker({color:'#16a34a'}).setLngLat(pos).addTo(map);else state.marker.setLngLat(pos);map.easeTo({center:pos,zoom:Math.max(map.getZoom(),15),bearing:Number.isFinite(p.coords.heading)?p.coords.heading:map.getBearing(),pitch:45,duration:700});updateInstruction(pos);if(state.original.length>1&&(state.mode==='gpx'||state.mode==='address')){const l=lineString(state.original),snap=nearestPointOnLine(l,point(pos),{units:'kilometers'}),off=distance(point(pos),snap,{units:'kilometers'}),loc=Number(snap.properties.location||0);state.progressKm=Math.max(state.progressKm,loc);state.offCount=off>.06?state.offCount+1:0;if(state.offCount>=3){state.offCount=0;smartRejoin(pos);}}else if(state.mode==='rejoin'&&state.original.length>1){const snap=nearestPointOnLine(lineString(state.original),point(pos),{units:'kilometers'});if(distance(point(pos),snap,{units:'kilometers'})<.04){const start=Math.max(state.progressKm,Number(snap.properties.location||0)),l=lineString(state.original),total=length(l,{units:'kilometers'}),coords=[];for(let km=start;km<total;km+=.05)coords.push(along(l,km,{units:'kilometers'}).geometry.coordinates);coords.push(state.original.at(-1));draw({coordinates:coords,distance:(total-start)*1000,time:0,instructions:[]},'gpx');status('GPX-route hervat');}}}
$('gps').onclick=async()=>{if(state.watch!==null){navigator.geolocation.clearWatch(state.watch);state.watch=null;$('gps').classList.remove('active');$('gps').textContent='Start GPS';return status('GPS gepauzeerd');}if(!navigator.geolocation)return status('GPS wordt niet ondersteund.');try{await navigator.wakeLock?.request('screen');}catch{}state.watch=navigator.geolocation.watchPosition(onPosition,e=>status(`GPS-fout: ${e.message}`),{enableHighAccuracy:true,maximumAge:1000,timeout:15000});$('gps').classList.add('active');$('gps').textContent='GPS aan';status('GPS actief');};
